### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Deadlore** [Zueripat/Reddit-Api#3]
![eckelhaft](https://user-images.githubusercontent.com/102439479/172028613-de81d393-9e4d-46fe-8162-a2eee2181644.png)
Guten Tag!

Wenn ich das Script laufe lasse, läuft es erst problemlos....Nach einer Zeit hört es Radom auf ein Subreddit zu herunterladen (hört auf beim z.B. 16 von 50 Bilder/Videos herunterladen).  Wenn ich das Script nochmals "Neustarte" dann geht es wieder, doch nach einer Zeit kommt das selbe Problem bei einem anderem Subreddit und so weiter...

**Comment by Zueripat** [comment]
Bitte nicht so sus
